// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/pepeunlimited/billing/internal/pkg/ent/instrument"
	"github.com/pepeunlimited/billing/internal/pkg/ent/predicate"
)

// InstrumentDelete is the builder for deleting a Instrument entity.
type InstrumentDelete struct {
	config
	predicates []predicate.Instrument
}

// Where adds a new predicate to the delete builder.
func (id *InstrumentDelete) Where(ps ...predicate.Instrument) *InstrumentDelete {
	id.predicates = append(id.predicates, ps...)
	return id
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (id *InstrumentDelete) Exec(ctx context.Context) (int, error) {
	return id.sqlExec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (id *InstrumentDelete) ExecX(ctx context.Context) int {
	n, err := id.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (id *InstrumentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: instrument.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: instrument.FieldID,
			},
		},
	}
	if ps := id.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, id.driver, _spec)
}

// InstrumentDeleteOne is the builder for deleting a single Instrument entity.
type InstrumentDeleteOne struct {
	id *InstrumentDelete
}

// Exec executes the deletion query.
func (ido *InstrumentDeleteOne) Exec(ctx context.Context) error {
	n, err := ido.id.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{instrument.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ido *InstrumentDeleteOne) ExecX(ctx context.Context) {
	ido.id.ExecX(ctx)
}
