// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/pepeunlimited/billing/internal/pkg/ent/item"
	"github.com/pepeunlimited/billing/internal/pkg/ent/orders"
	"github.com/pepeunlimited/billing/internal/pkg/ent/predicate"
)

// ItemUpdate is the builder for updating Item entities.
type ItemUpdate struct {
	config
	price_id      *int64
	addprice_id   *int64
	clearprice_id bool
	plan_id       *int64
	addplan_id    *int64
	clearplan_id  bool
	quantity      *uint8
	addquantity   *uint8
	orders        map[int]struct{}
	clearedOrders bool
	predicates    []predicate.Item
}

// Where adds a new predicate for the builder.
func (iu *ItemUpdate) Where(ps ...predicate.Item) *ItemUpdate {
	iu.predicates = append(iu.predicates, ps...)
	return iu
}

// SetPriceID sets the price_id field.
func (iu *ItemUpdate) SetPriceID(i int64) *ItemUpdate {
	iu.price_id = &i
	iu.addprice_id = nil
	return iu
}

// SetNillablePriceID sets the price_id field if the given value is not nil.
func (iu *ItemUpdate) SetNillablePriceID(i *int64) *ItemUpdate {
	if i != nil {
		iu.SetPriceID(*i)
	}
	return iu
}

// AddPriceID adds i to price_id.
func (iu *ItemUpdate) AddPriceID(i int64) *ItemUpdate {
	if iu.addprice_id == nil {
		iu.addprice_id = &i
	} else {
		*iu.addprice_id += i
	}
	return iu
}

// ClearPriceID clears the value of price_id.
func (iu *ItemUpdate) ClearPriceID() *ItemUpdate {
	iu.price_id = nil
	iu.clearprice_id = true
	return iu
}

// SetPlanID sets the plan_id field.
func (iu *ItemUpdate) SetPlanID(i int64) *ItemUpdate {
	iu.plan_id = &i
	iu.addplan_id = nil
	return iu
}

// SetNillablePlanID sets the plan_id field if the given value is not nil.
func (iu *ItemUpdate) SetNillablePlanID(i *int64) *ItemUpdate {
	if i != nil {
		iu.SetPlanID(*i)
	}
	return iu
}

// AddPlanID adds i to plan_id.
func (iu *ItemUpdate) AddPlanID(i int64) *ItemUpdate {
	if iu.addplan_id == nil {
		iu.addplan_id = &i
	} else {
		*iu.addplan_id += i
	}
	return iu
}

// ClearPlanID clears the value of plan_id.
func (iu *ItemUpdate) ClearPlanID() *ItemUpdate {
	iu.plan_id = nil
	iu.clearplan_id = true
	return iu
}

// SetQuantity sets the quantity field.
func (iu *ItemUpdate) SetQuantity(u uint8) *ItemUpdate {
	iu.quantity = &u
	iu.addquantity = nil
	return iu
}

// SetNillableQuantity sets the quantity field if the given value is not nil.
func (iu *ItemUpdate) SetNillableQuantity(u *uint8) *ItemUpdate {
	if u != nil {
		iu.SetQuantity(*u)
	}
	return iu
}

// AddQuantity adds u to quantity.
func (iu *ItemUpdate) AddQuantity(u uint8) *ItemUpdate {
	if iu.addquantity == nil {
		iu.addquantity = &u
	} else {
		*iu.addquantity += u
	}
	return iu
}

// SetOrdersID sets the orders edge to Orders by id.
func (iu *ItemUpdate) SetOrdersID(id int) *ItemUpdate {
	if iu.orders == nil {
		iu.orders = make(map[int]struct{})
	}
	iu.orders[id] = struct{}{}
	return iu
}

// SetNillableOrdersID sets the orders edge to Orders by id if the given value is not nil.
func (iu *ItemUpdate) SetNillableOrdersID(id *int) *ItemUpdate {
	if id != nil {
		iu = iu.SetOrdersID(*id)
	}
	return iu
}

// SetOrders sets the orders edge to Orders.
func (iu *ItemUpdate) SetOrders(o *Orders) *ItemUpdate {
	return iu.SetOrdersID(o.ID)
}

// ClearOrders clears the orders edge to Orders.
func (iu *ItemUpdate) ClearOrders() *ItemUpdate {
	iu.clearedOrders = true
	return iu
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (iu *ItemUpdate) Save(ctx context.Context) (int, error) {
	if len(iu.orders) > 1 {
		return 0, errors.New("ent: multiple assignments on a unique edge \"orders\"")
	}
	return iu.sqlSave(ctx)
}

// SaveX is like Save, but panics if an error occurs.
func (iu *ItemUpdate) SaveX(ctx context.Context) int {
	affected, err := iu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (iu *ItemUpdate) Exec(ctx context.Context) error {
	_, err := iu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iu *ItemUpdate) ExecX(ctx context.Context) {
	if err := iu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (iu *ItemUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   item.Table,
			Columns: item.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: item.FieldID,
			},
		},
	}
	if ps := iu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value := iu.price_id; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  *value,
			Column: item.FieldPriceID,
		})
	}
	if value := iu.addprice_id; value != nil {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  *value,
			Column: item.FieldPriceID,
		})
	}
	if iu.clearprice_id {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Column: item.FieldPriceID,
		})
	}
	if value := iu.plan_id; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  *value,
			Column: item.FieldPlanID,
		})
	}
	if value := iu.addplan_id; value != nil {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  *value,
			Column: item.FieldPlanID,
		})
	}
	if iu.clearplan_id {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Column: item.FieldPlanID,
		})
	}
	if value := iu.quantity; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint8,
			Value:  *value,
			Column: item.FieldQuantity,
		})
	}
	if value := iu.addquantity; value != nil {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint8,
			Value:  *value,
			Column: item.FieldQuantity,
		})
	}
	if iu.clearedOrders {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   item.OrdersTable,
			Columns: []string{item.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: orders.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iu.orders; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   item.OrdersTable,
			Columns: []string{item.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: orders.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, iu.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// ItemUpdateOne is the builder for updating a single Item entity.
type ItemUpdateOne struct {
	config
	id            int
	price_id      *int64
	addprice_id   *int64
	clearprice_id bool
	plan_id       *int64
	addplan_id    *int64
	clearplan_id  bool
	quantity      *uint8
	addquantity   *uint8
	orders        map[int]struct{}
	clearedOrders bool
}

// SetPriceID sets the price_id field.
func (iuo *ItemUpdateOne) SetPriceID(i int64) *ItemUpdateOne {
	iuo.price_id = &i
	iuo.addprice_id = nil
	return iuo
}

// SetNillablePriceID sets the price_id field if the given value is not nil.
func (iuo *ItemUpdateOne) SetNillablePriceID(i *int64) *ItemUpdateOne {
	if i != nil {
		iuo.SetPriceID(*i)
	}
	return iuo
}

// AddPriceID adds i to price_id.
func (iuo *ItemUpdateOne) AddPriceID(i int64) *ItemUpdateOne {
	if iuo.addprice_id == nil {
		iuo.addprice_id = &i
	} else {
		*iuo.addprice_id += i
	}
	return iuo
}

// ClearPriceID clears the value of price_id.
func (iuo *ItemUpdateOne) ClearPriceID() *ItemUpdateOne {
	iuo.price_id = nil
	iuo.clearprice_id = true
	return iuo
}

// SetPlanID sets the plan_id field.
func (iuo *ItemUpdateOne) SetPlanID(i int64) *ItemUpdateOne {
	iuo.plan_id = &i
	iuo.addplan_id = nil
	return iuo
}

// SetNillablePlanID sets the plan_id field if the given value is not nil.
func (iuo *ItemUpdateOne) SetNillablePlanID(i *int64) *ItemUpdateOne {
	if i != nil {
		iuo.SetPlanID(*i)
	}
	return iuo
}

// AddPlanID adds i to plan_id.
func (iuo *ItemUpdateOne) AddPlanID(i int64) *ItemUpdateOne {
	if iuo.addplan_id == nil {
		iuo.addplan_id = &i
	} else {
		*iuo.addplan_id += i
	}
	return iuo
}

// ClearPlanID clears the value of plan_id.
func (iuo *ItemUpdateOne) ClearPlanID() *ItemUpdateOne {
	iuo.plan_id = nil
	iuo.clearplan_id = true
	return iuo
}

// SetQuantity sets the quantity field.
func (iuo *ItemUpdateOne) SetQuantity(u uint8) *ItemUpdateOne {
	iuo.quantity = &u
	iuo.addquantity = nil
	return iuo
}

// SetNillableQuantity sets the quantity field if the given value is not nil.
func (iuo *ItemUpdateOne) SetNillableQuantity(u *uint8) *ItemUpdateOne {
	if u != nil {
		iuo.SetQuantity(*u)
	}
	return iuo
}

// AddQuantity adds u to quantity.
func (iuo *ItemUpdateOne) AddQuantity(u uint8) *ItemUpdateOne {
	if iuo.addquantity == nil {
		iuo.addquantity = &u
	} else {
		*iuo.addquantity += u
	}
	return iuo
}

// SetOrdersID sets the orders edge to Orders by id.
func (iuo *ItemUpdateOne) SetOrdersID(id int) *ItemUpdateOne {
	if iuo.orders == nil {
		iuo.orders = make(map[int]struct{})
	}
	iuo.orders[id] = struct{}{}
	return iuo
}

// SetNillableOrdersID sets the orders edge to Orders by id if the given value is not nil.
func (iuo *ItemUpdateOne) SetNillableOrdersID(id *int) *ItemUpdateOne {
	if id != nil {
		iuo = iuo.SetOrdersID(*id)
	}
	return iuo
}

// SetOrders sets the orders edge to Orders.
func (iuo *ItemUpdateOne) SetOrders(o *Orders) *ItemUpdateOne {
	return iuo.SetOrdersID(o.ID)
}

// ClearOrders clears the orders edge to Orders.
func (iuo *ItemUpdateOne) ClearOrders() *ItemUpdateOne {
	iuo.clearedOrders = true
	return iuo
}

// Save executes the query and returns the updated entity.
func (iuo *ItemUpdateOne) Save(ctx context.Context) (*Item, error) {
	if len(iuo.orders) > 1 {
		return nil, errors.New("ent: multiple assignments on a unique edge \"orders\"")
	}
	return iuo.sqlSave(ctx)
}

// SaveX is like Save, but panics if an error occurs.
func (iuo *ItemUpdateOne) SaveX(ctx context.Context) *Item {
	i, err := iuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return i
}

// Exec executes the query on the entity.
func (iuo *ItemUpdateOne) Exec(ctx context.Context) error {
	_, err := iuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iuo *ItemUpdateOne) ExecX(ctx context.Context) {
	if err := iuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (iuo *ItemUpdateOne) sqlSave(ctx context.Context) (i *Item, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   item.Table,
			Columns: item.Columns,
			ID: &sqlgraph.FieldSpec{
				Value:  iuo.id,
				Type:   field.TypeInt,
				Column: item.FieldID,
			},
		},
	}
	if value := iuo.price_id; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  *value,
			Column: item.FieldPriceID,
		})
	}
	if value := iuo.addprice_id; value != nil {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  *value,
			Column: item.FieldPriceID,
		})
	}
	if iuo.clearprice_id {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Column: item.FieldPriceID,
		})
	}
	if value := iuo.plan_id; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  *value,
			Column: item.FieldPlanID,
		})
	}
	if value := iuo.addplan_id; value != nil {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  *value,
			Column: item.FieldPlanID,
		})
	}
	if iuo.clearplan_id {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Column: item.FieldPlanID,
		})
	}
	if value := iuo.quantity; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint8,
			Value:  *value,
			Column: item.FieldQuantity,
		})
	}
	if value := iuo.addquantity; value != nil {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint8,
			Value:  *value,
			Column: item.FieldQuantity,
		})
	}
	if iuo.clearedOrders {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   item.OrdersTable,
			Columns: []string{item.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: orders.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iuo.orders; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   item.OrdersTable,
			Columns: []string{item.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: orders.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	i = &Item{config: iuo.config}
	_spec.Assign = i.assignValues
	_spec.ScanValues = i.scanValues()
	if err = sqlgraph.UpdateNode(ctx, iuo.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return i, nil
}
