// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/pepeunlimited/billing/internal/pkg/ent/orders"
)

// OrderTXsCreate is the builder for creating a OrderTXs entity.
type OrderTXsCreate struct {
	config
	orders map[int]struct{}
}

// SetOrdersID sets the orders edge to Orders by id.
func (ordertxscreate *OrderTXsCreate) SetOrdersID(id int) *OrderTXsCreate {
	if ordertxscreate.orders == nil {
		ordertxscreate.orders = make(map[int]struct{})
	}
	ordertxscreate.orders[id] = struct{}{}
	return ordertxscreate
}

// SetNillableOrdersID sets the orders edge to Orders by id if the given value is not nil.
func (ordertxscreate *OrderTXsCreate) SetNillableOrdersID(id *int) *OrderTXsCreate {
	if id != nil {
		ordertxscreate = ordertxscreate.SetOrdersID(*id)
	}
	return ordertxscreate
}

// SetOrders sets the orders edge to Orders.
func (ordertxscreate *OrderTXsCreate) SetOrders(o *Orders) *OrderTXsCreate {
	return ordertxscreate.SetOrdersID(o.ID)
}

// Save creates the OrderTXs in the database.
func (ordertxscreate *OrderTXsCreate) Save(ctx context.Context) (*OrderTXs, error) {
	if len(ordertxscreate.orders) > 1 {
		return nil, errors.New("ent: multiple assignments on a unique edge \"orders\"")
	}
	return ordertxscreate.sqlSave(ctx)
}

// SaveX calls Save and panics if Save returns an error.
func (ordertxscreate *OrderTXsCreate) SaveX(ctx context.Context) *OrderTXs {
	v, err := ordertxscreate.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ordertxscreate *OrderTXsCreate) sqlSave(ctx context.Context) (*OrderTXs, error) {
	var (
		ordertxs = &OrderTXs{config: ordertxscreate.config}
		_spec    = &sqlgraph.CreateSpec{
			Table: ordertxs.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: ordertxs.FieldID,
			},
		}
	)
	if nodes := ordertxscreate.orders; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ordertxs.OrdersTable,
			Columns: []string{ordertxs.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: orders.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if err := sqlgraph.CreateNode(ctx, ordertxscreate.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	ordertxs.ID = int(id)
	return ordertxs, nil
}
