// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/pepeunlimited/billing/internal/pkg/ent/paymentinstruments"
	"github.com/pepeunlimited/billing/internal/pkg/ent/predicate"
)

// PaymentInstrumentsDelete is the builder for deleting a PaymentInstruments entity.
type PaymentInstrumentsDelete struct {
	config
	predicates []predicate.PaymentInstruments
}

// Where adds a new predicate to the delete builder.
func (pid *PaymentInstrumentsDelete) Where(ps ...predicate.PaymentInstruments) *PaymentInstrumentsDelete {
	pid.predicates = append(pid.predicates, ps...)
	return pid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pid *PaymentInstrumentsDelete) Exec(ctx context.Context) (int, error) {
	return pid.sqlExec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (pid *PaymentInstrumentsDelete) ExecX(ctx context.Context) int {
	n, err := pid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pid *PaymentInstrumentsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: paymentinstruments.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: paymentinstruments.FieldID,
			},
		},
	}
	if ps := pid.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, pid.driver, _spec)
}

// PaymentInstrumentsDeleteOne is the builder for deleting a single PaymentInstruments entity.
type PaymentInstrumentsDeleteOne struct {
	pid *PaymentInstrumentsDelete
}

// Exec executes the deletion query.
func (pido *PaymentInstrumentsDeleteOne) Exec(ctx context.Context) error {
	n, err := pido.pid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{paymentinstruments.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pido *PaymentInstrumentsDeleteOne) ExecX(ctx context.Context) {
	pido.pid.ExecX(ctx)
}
