// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/pepeunlimited/billing/internal/pkg/ent/instrument"
	"github.com/pepeunlimited/billing/internal/pkg/ent/orders"
	"github.com/pepeunlimited/billing/internal/pkg/ent/payment"
)

// PaymentCreate is the builder for creating a Payment entity.
type PaymentCreate struct {
	config
	orders      map[int]struct{}
	instruments map[int]struct{}
}

// SetOrdersID sets the orders edge to Orders by id.
func (pc *PaymentCreate) SetOrdersID(id int) *PaymentCreate {
	if pc.orders == nil {
		pc.orders = make(map[int]struct{})
	}
	pc.orders[id] = struct{}{}
	return pc
}

// SetNillableOrdersID sets the orders edge to Orders by id if the given value is not nil.
func (pc *PaymentCreate) SetNillableOrdersID(id *int) *PaymentCreate {
	if id != nil {
		pc = pc.SetOrdersID(*id)
	}
	return pc
}

// SetOrders sets the orders edge to Orders.
func (pc *PaymentCreate) SetOrders(o *Orders) *PaymentCreate {
	return pc.SetOrdersID(o.ID)
}

// SetInstrumentsID sets the instruments edge to Instrument by id.
func (pc *PaymentCreate) SetInstrumentsID(id int) *PaymentCreate {
	if pc.instruments == nil {
		pc.instruments = make(map[int]struct{})
	}
	pc.instruments[id] = struct{}{}
	return pc
}

// SetNillableInstrumentsID sets the instruments edge to Instrument by id if the given value is not nil.
func (pc *PaymentCreate) SetNillableInstrumentsID(id *int) *PaymentCreate {
	if id != nil {
		pc = pc.SetInstrumentsID(*id)
	}
	return pc
}

// SetInstruments sets the instruments edge to Instrument.
func (pc *PaymentCreate) SetInstruments(i *Instrument) *PaymentCreate {
	return pc.SetInstrumentsID(i.ID)
}

// Save creates the Payment in the database.
func (pc *PaymentCreate) Save(ctx context.Context) (*Payment, error) {
	if len(pc.orders) > 1 {
		return nil, errors.New("ent: multiple assignments on a unique edge \"orders\"")
	}
	if len(pc.instruments) > 1 {
		return nil, errors.New("ent: multiple assignments on a unique edge \"instruments\"")
	}
	return pc.sqlSave(ctx)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PaymentCreate) SaveX(ctx context.Context) *Payment {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pc *PaymentCreate) sqlSave(ctx context.Context) (*Payment, error) {
	var (
		pa    = &Payment{config: pc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: payment.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: payment.FieldID,
			},
		}
	)
	if nodes := pc.orders; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   payment.OrdersTable,
			Columns: []string{payment.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: orders.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pc.instruments; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.InstrumentsTable,
			Columns: []string{payment.InstrumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: instrument.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	pa.ID = int(id)
	return pa, nil
}
