// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/pepeunlimited/billing/internal/pkg/ent/subscriptions"
)

// Subscriptions is the model entity for the Subscriptions schema.
type Subscriptions struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubscriptionsQuery when eager-loading is set.
	Edges SubscriptionsEdges `json:"edges"`
}

// SubscriptionsEdges holds the relations/edges for other nodes in the graph.
type SubscriptionsEdges struct {
	// Plans holds the value of the plans edge.
	Plans []*Plans
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PlansOrErr returns the Plans value or an error if the edge
// was not loaded in eager-loading.
func (e SubscriptionsEdges) PlansOrErr() ([]*Plans, error) {
	if e.loadedTypes[0] {
		return e.Plans, nil
	}
	return nil, &NotLoadedError{edge: "plans"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Subscriptions) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // id
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Subscriptions fields.
func (s *Subscriptions) assignValues(values ...interface{}) error {
	if m, n := len(values), len(subscriptions.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	s.ID = int(value.Int64)
	values = values[1:]
	return nil
}

// QueryPlans queries the plans edge of the Subscriptions.
func (s *Subscriptions) QueryPlans() *PlansQuery {
	return (&SubscriptionsClient{s.config}).QueryPlans(s)
}

// Update returns a builder for updating this Subscriptions.
// Note that, you need to call Subscriptions.Unwrap() before calling this method, if this Subscriptions
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Subscriptions) Update() *SubscriptionsUpdateOne {
	return (&SubscriptionsClient{s.config}).UpdateOne(s)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (s *Subscriptions) Unwrap() *Subscriptions {
	tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Subscriptions is not a transactional entity")
	}
	s.config.driver = tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Subscriptions) String() string {
	var builder strings.Builder
	builder.WriteString("Subscriptions(")
	builder.WriteString(fmt.Sprintf("id=%v", s.ID))
	builder.WriteByte(')')
	return builder.String()
}

// SubscriptionsSlice is a parsable slice of Subscriptions.
type SubscriptionsSlice []*Subscriptions

func (s SubscriptionsSlice) config(cfg config) {
	for _i := range s {
		s[_i].config = cfg
	}
}
