// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/pepeunlimited/billing/internal/pkg/ent/orders"
	"github.com/pepeunlimited/billing/internal/pkg/ent/txs"
)

// Txs is the model entity for the Txs schema.
type Txs struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TxsQuery when eager-loading is set.
	Edges      TxsEdges `json:"edges"`
	orders_txs *int
}

// TxsEdges holds the relations/edges for other nodes in the graph.
type TxsEdges struct {
	// Orders holds the value of the orders edge.
	Orders *Orders
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// OrdersOrErr returns the Orders value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TxsEdges) OrdersOrErr() (*Orders, error) {
	if e.loadedTypes[0] {
		if e.Orders == nil {
			// The edge orders was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: orders.Label}
		}
		return e.Orders, nil
	}
	return nil, &NotLoadedError{edge: "orders"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Txs) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // status
		&sql.NullTime{},   // created_at
	}
}

// fkValues returns the types for scanning foreign-keys values from sql.Rows.
func (*Txs) fkValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // orders_txs
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Txs fields.
func (t *Txs) assignValues(values ...interface{}) error {
	if m, n := len(values), len(txs.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	t.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field status", values[0])
	} else if value.Valid {
		t.Status = value.String
	}
	if value, ok := values[1].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field created_at", values[1])
	} else if value.Valid {
		t.CreatedAt = value.Time
	}
	values = values[2:]
	if len(values) == len(txs.ForeignKeys) {
		if value, ok := values[0].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field orders_txs", value)
		} else if value.Valid {
			t.orders_txs = new(int)
			*t.orders_txs = int(value.Int64)
		}
	}
	return nil
}

// QueryOrders queries the orders edge of the Txs.
func (t *Txs) QueryOrders() *OrdersQuery {
	return (&TxsClient{t.config}).QueryOrders(t)
}

// Update returns a builder for updating this Txs.
// Note that, you need to call Txs.Unwrap() before calling this method, if this Txs
// was returned from a transaction, and the transaction was committed or rolled back.
func (t *Txs) Update() *TxsUpdateOne {
	return (&TxsClient{t.config}).UpdateOne(t)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (t *Txs) Unwrap() *Txs {
	tx, ok := t.config.driver.(*txDriver)
	if !ok {
		panic("ent: Txs is not a transactional entity")
	}
	t.config.driver = tx.drv
	return t
}

// String implements the fmt.Stringer.
func (t *Txs) String() string {
	var builder strings.Builder
	builder.WriteString("Txs(")
	builder.WriteString(fmt.Sprintf("id=%v", t.ID))
	builder.WriteString(", status=")
	builder.WriteString(t.Status)
	builder.WriteString(", created_at=")
	builder.WriteString(t.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TxsSlice is a parsable slice of Txs.
type TxsSlice []*Txs

func (t TxsSlice) config(cfg config) {
	for _i := range t {
		t[_i].config = cfg
	}
}
