// Code generated by entc, DO NOT EDIT.

package orderitems

const (
	// Label holds the string label denoting the orderitems type in the database.
	Label = "order_items"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// Table holds the table name of the orderitems in the database.
	Table = "order_items"
	// OrdersTable is the table the holds the orders relation/edge.
	OrdersTable = "order_items"
	// OrdersInverseTable is the table name for the Orders entity.
	// It exists in this package in order to avoid circular dependency with the "orders" package.
	OrdersInverseTable = "orders"
	// OrdersColumn is the table column denoting the orders relation/edge.
	OrdersColumn = "orders_order_items"
)

// Columns holds all SQL columns for orderitems fields.
var Columns = []string{
	FieldID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the OrderItems type.
var ForeignKeys = []string{
	"orders_order_items",
}
