// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/pepeunlimited/billing/internal/pkg/ent/item"

	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// PaymentInstrumentsColumns holds the columns for the "payment_instruments" table.
	PaymentInstrumentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "type", Type: field.TypeString, Unique: true, Size: 12},
		{Name: "type_i18n_id", Type: field.TypeInt64, Nullable: true},
	}
	// PaymentInstrumentsTable holds the schema information for the "payment_instruments" table.
	PaymentInstrumentsTable = &schema.Table{
		Name:        "payment_instruments",
		Columns:     PaymentInstrumentsColumns,
		PrimaryKey:  []*schema.Column{PaymentInstrumentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// OrderItemsColumns holds the columns for the "order_items" table.
	OrderItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "price_id", Type: field.TypeInt64},
		{Name: "quantity", Type: field.TypeUint8, Default: item.DefaultQuantity},
		{Name: "orders_items", Type: field.TypeInt, Nullable: true},
	}
	// OrderItemsTable holds the schema information for the "order_items" table.
	OrderItemsTable = &schema.Table{
		Name:       "order_items",
		Columns:    OrderItemsColumns,
		PrimaryKey: []*schema.Column{OrderItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "order_items_orders_items",
				Columns: []*schema.Column{OrderItemsColumns[3]},

				RefColumns: []*schema.Column{OrdersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// OrdersColumns holds the columns for the "orders" table.
	OrdersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "payment_orders", Type: field.TypeInt, Unique: true, Nullable: true},
	}
	// OrdersTable holds the schema information for the "orders" table.
	OrdersTable = &schema.Table{
		Name:       "orders",
		Columns:    OrdersColumns,
		PrimaryKey: []*schema.Column{OrdersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "orders_payments_orders",
				Columns: []*schema.Column{OrdersColumns[3]},

				RefColumns: []*schema.Column{PaymentsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// PaymentsColumns holds the columns for the "payments" table.
	PaymentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "instrument_payments", Type: field.TypeInt, Nullable: true},
	}
	// PaymentsTable holds the schema information for the "payments" table.
	PaymentsTable = &schema.Table{
		Name:       "payments",
		Columns:    PaymentsColumns,
		PrimaryKey: []*schema.Column{PaymentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "payments_payment_instruments_payments",
				Columns: []*schema.Column{PaymentsColumns[1]},

				RefColumns: []*schema.Column{PaymentInstrumentsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// PlansColumns holds the columns for the "plans" table.
	PlansColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title_i18n_id", Type: field.TypeInt64},
		{Name: "price_id", Type: field.TypeInt64, Unique: true},
		{Name: "start_at", Type: field.TypeTime},
		{Name: "end_at", Type: field.TypeTime},
		{Name: "length", Type: field.TypeUint8},
		{Name: "unit", Type: field.TypeString, Size: 7},
	}
	// PlansTable holds the schema information for the "plans" table.
	PlansTable = &schema.Table{
		Name:        "plans",
		Columns:     PlansColumns,
		PrimaryKey:  []*schema.Column{PlansColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// SubscriptionsColumns holds the columns for the "subscriptions" table.
	SubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "start_at", Type: field.TypeTime},
		{Name: "end_at", Type: field.TypeTime},
		{Name: "plan_subscriptions", Type: field.TypeInt, Nullable: true},
	}
	// SubscriptionsTable holds the schema information for the "subscriptions" table.
	SubscriptionsTable = &schema.Table{
		Name:       "subscriptions",
		Columns:    SubscriptionsColumns,
		PrimaryKey: []*schema.Column{SubscriptionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "subscriptions_plans_subscriptions",
				Columns: []*schema.Column{SubscriptionsColumns[4]},

				RefColumns: []*schema.Column{PlansColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// OrderTxsColumns holds the columns for the "order_txs" table.
	OrderTxsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "status", Type: field.TypeString, Size: 8},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "orders_txs", Type: field.TypeInt, Nullable: true},
	}
	// OrderTxsTable holds the schema information for the "order_txs" table.
	OrderTxsTable = &schema.Table{
		Name:       "order_txs",
		Columns:    OrderTxsColumns,
		PrimaryKey: []*schema.Column{OrderTxsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "order_txs_orders_txs",
				Columns: []*schema.Column{OrderTxsColumns[3]},

				RefColumns: []*schema.Column{OrdersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PaymentInstrumentsTable,
		OrderItemsTable,
		OrdersTable,
		PaymentsTable,
		PlansTable,
		SubscriptionsTable,
		OrderTxsTable,
	}
)

func init() {
	OrderItemsTable.ForeignKeys[0].RefTable = OrdersTable
	OrdersTable.ForeignKeys[0].RefTable = PaymentsTable
	PaymentsTable.ForeignKeys[0].RefTable = PaymentInstrumentsTable
	SubscriptionsTable.ForeignKeys[0].RefTable = PlansTable
	OrderTxsTable.ForeignKeys[0].RefTable = OrdersTable
}
