// Code generated by entc, DO NOT EDIT.

package subscriptions

const (
	// Label holds the string label denoting the subscriptions type in the database.
	Label = "subscriptions"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// Table holds the table name of the subscriptions in the database.
	Table = "subscriptions"
	// PlansTable is the table the holds the plans relation/edge.
	PlansTable = "plans"
	// PlansInverseTable is the table name for the Plans entity.
	// It exists in this package in order to avoid circular dependency with the "plans" package.
	PlansInverseTable = "plans"
	// PlansColumn is the table column denoting the plans relation/edge.
	PlansColumn = "subscriptions_plans"
)

// Columns holds all SQL columns for subscriptions fields.
var Columns = []string{
	FieldID,
}
