// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payment.proto

package paymentrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreatePaymentParams struct {
	OrderId              int64    `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentInstrumentId  int64    `protobuf:"varint,2,opt,name=payment_instrument_id,json=paymentInstrumentId,proto3" json:"payment_instrument_id,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePaymentParams) Reset()         { *m = CreatePaymentParams{} }
func (m *CreatePaymentParams) String() string { return proto.CompactTextString(m) }
func (*CreatePaymentParams) ProtoMessage()    {}
func (*CreatePaymentParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{0}
}

func (m *CreatePaymentParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePaymentParams.Unmarshal(m, b)
}
func (m *CreatePaymentParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePaymentParams.Marshal(b, m, deterministic)
}
func (m *CreatePaymentParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePaymentParams.Merge(m, src)
}
func (m *CreatePaymentParams) XXX_Size() int {
	return xxx_messageInfo_CreatePaymentParams.Size(m)
}
func (m *CreatePaymentParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePaymentParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePaymentParams proto.InternalMessageInfo

func (m *CreatePaymentParams) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *CreatePaymentParams) GetPaymentInstrumentId() int64 {
	if m != nil {
		return m.PaymentInstrumentId
	}
	return 0
}

func (m *CreatePaymentParams) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type Payment struct {
	PaymentInstrumentId  int64    `protobuf:"varint,1,opt,name=payment_instrument_id,json=paymentInstrumentId,proto3" json:"payment_instrument_id,omitempty"`
	OrderId              int64    `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Id                   int64    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payment) Reset()         { *m = Payment{} }
func (m *Payment) String() string { return proto.CompactTextString(m) }
func (*Payment) ProtoMessage()    {}
func (*Payment) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{1}
}

func (m *Payment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payment.Unmarshal(m, b)
}
func (m *Payment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payment.Marshal(b, m, deterministic)
}
func (m *Payment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payment.Merge(m, src)
}
func (m *Payment) XXX_Size() int {
	return xxx_messageInfo_Payment.Size(m)
}
func (m *Payment) XXX_DiscardUnknown() {
	xxx_messageInfo_Payment.DiscardUnknown(m)
}

var xxx_messageInfo_Payment proto.InternalMessageInfo

func (m *Payment) GetPaymentInstrumentId() int64 {
	if m != nil {
		return m.PaymentInstrumentId
	}
	return 0
}

func (m *Payment) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *Payment) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetPaymentParams struct {
	PaymentId            int64    `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId              int64    `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPaymentParams) Reset()         { *m = GetPaymentParams{} }
func (m *GetPaymentParams) String() string { return proto.CompactTextString(m) }
func (*GetPaymentParams) ProtoMessage()    {}
func (*GetPaymentParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{2}
}

func (m *GetPaymentParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPaymentParams.Unmarshal(m, b)
}
func (m *GetPaymentParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPaymentParams.Marshal(b, m, deterministic)
}
func (m *GetPaymentParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPaymentParams.Merge(m, src)
}
func (m *GetPaymentParams) XXX_Size() int {
	return xxx_messageInfo_GetPaymentParams.Size(m)
}
func (m *GetPaymentParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPaymentParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetPaymentParams proto.InternalMessageInfo

func (m *GetPaymentParams) GetPaymentId() int64 {
	if m != nil {
		return m.PaymentId
	}
	return 0
}

func (m *GetPaymentParams) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetPaymentParams) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

type GetPaymentsParams struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken            int64    `protobuf:"varint,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPaymentsParams) Reset()         { *m = GetPaymentsParams{} }
func (m *GetPaymentsParams) String() string { return proto.CompactTextString(m) }
func (*GetPaymentsParams) ProtoMessage()    {}
func (*GetPaymentsParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{3}
}

func (m *GetPaymentsParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPaymentsParams.Unmarshal(m, b)
}
func (m *GetPaymentsParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPaymentsParams.Marshal(b, m, deterministic)
}
func (m *GetPaymentsParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPaymentsParams.Merge(m, src)
}
func (m *GetPaymentsParams) XXX_Size() int {
	return xxx_messageInfo_GetPaymentsParams.Size(m)
}
func (m *GetPaymentsParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPaymentsParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetPaymentsParams proto.InternalMessageInfo

func (m *GetPaymentsParams) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetPaymentsParams) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetPaymentsParams) GetPageToken() int64 {
	if m != nil {
		return m.PageToken
	}
	return 0
}

type GetPaymentsResponse struct {
	Payments             []*Payment `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	NextPageToken        int64      `protobuf:"varint,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetPaymentsResponse) Reset()         { *m = GetPaymentsResponse{} }
func (m *GetPaymentsResponse) String() string { return proto.CompactTextString(m) }
func (*GetPaymentsResponse) ProtoMessage()    {}
func (*GetPaymentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{4}
}

func (m *GetPaymentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPaymentsResponse.Unmarshal(m, b)
}
func (m *GetPaymentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPaymentsResponse.Marshal(b, m, deterministic)
}
func (m *GetPaymentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPaymentsResponse.Merge(m, src)
}
func (m *GetPaymentsResponse) XXX_Size() int {
	return xxx_messageInfo_GetPaymentsResponse.Size(m)
}
func (m *GetPaymentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPaymentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPaymentsResponse proto.InternalMessageInfo

func (m *GetPaymentsResponse) GetPayments() []*Payment {
	if m != nil {
		return m.Payments
	}
	return nil
}

func (m *GetPaymentsResponse) GetNextPageToken() int64 {
	if m != nil {
		return m.NextPageToken
	}
	return 0
}

type CreatePaymentInstrumentParams struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePaymentInstrumentParams) Reset()         { *m = CreatePaymentInstrumentParams{} }
func (m *CreatePaymentInstrumentParams) String() string { return proto.CompactTextString(m) }
func (*CreatePaymentInstrumentParams) ProtoMessage()    {}
func (*CreatePaymentInstrumentParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{5}
}

func (m *CreatePaymentInstrumentParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePaymentInstrumentParams.Unmarshal(m, b)
}
func (m *CreatePaymentInstrumentParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePaymentInstrumentParams.Marshal(b, m, deterministic)
}
func (m *CreatePaymentInstrumentParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePaymentInstrumentParams.Merge(m, src)
}
func (m *CreatePaymentInstrumentParams) XXX_Size() int {
	return xxx_messageInfo_CreatePaymentInstrumentParams.Size(m)
}
func (m *CreatePaymentInstrumentParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePaymentInstrumentParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePaymentInstrumentParams proto.InternalMessageInfo

func (m *CreatePaymentInstrumentParams) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type PaymentInstrument struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	TypeI18NId           int64    `protobuf:"varint,3,opt,name=type_i18n_id,json=typeI18nId,proto3" json:"type_i18n_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentInstrument) Reset()         { *m = PaymentInstrument{} }
func (m *PaymentInstrument) String() string { return proto.CompactTextString(m) }
func (*PaymentInstrument) ProtoMessage()    {}
func (*PaymentInstrument) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{6}
}

func (m *PaymentInstrument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentInstrument.Unmarshal(m, b)
}
func (m *PaymentInstrument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentInstrument.Marshal(b, m, deterministic)
}
func (m *PaymentInstrument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentInstrument.Merge(m, src)
}
func (m *PaymentInstrument) XXX_Size() int {
	return xxx_messageInfo_PaymentInstrument.Size(m)
}
func (m *PaymentInstrument) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentInstrument.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentInstrument proto.InternalMessageInfo

func (m *PaymentInstrument) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PaymentInstrument) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PaymentInstrument) GetTypeI18NId() int64 {
	if m != nil {
		return m.TypeI18NId
	}
	return 0
}

type DeletePaymentInstrumentParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePaymentInstrumentParams) Reset()         { *m = DeletePaymentInstrumentParams{} }
func (m *DeletePaymentInstrumentParams) String() string { return proto.CompactTextString(m) }
func (*DeletePaymentInstrumentParams) ProtoMessage()    {}
func (*DeletePaymentInstrumentParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{7}
}

func (m *DeletePaymentInstrumentParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePaymentInstrumentParams.Unmarshal(m, b)
}
func (m *DeletePaymentInstrumentParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePaymentInstrumentParams.Marshal(b, m, deterministic)
}
func (m *DeletePaymentInstrumentParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePaymentInstrumentParams.Merge(m, src)
}
func (m *DeletePaymentInstrumentParams) XXX_Size() int {
	return xxx_messageInfo_DeletePaymentInstrumentParams.Size(m)
}
func (m *DeletePaymentInstrumentParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePaymentInstrumentParams.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePaymentInstrumentParams proto.InternalMessageInfo

type GetPaymentInstrumentParams struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPaymentInstrumentParams) Reset()         { *m = GetPaymentInstrumentParams{} }
func (m *GetPaymentInstrumentParams) String() string { return proto.CompactTextString(m) }
func (*GetPaymentInstrumentParams) ProtoMessage()    {}
func (*GetPaymentInstrumentParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{8}
}

func (m *GetPaymentInstrumentParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPaymentInstrumentParams.Unmarshal(m, b)
}
func (m *GetPaymentInstrumentParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPaymentInstrumentParams.Marshal(b, m, deterministic)
}
func (m *GetPaymentInstrumentParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPaymentInstrumentParams.Merge(m, src)
}
func (m *GetPaymentInstrumentParams) XXX_Size() int {
	return xxx_messageInfo_GetPaymentInstrumentParams.Size(m)
}
func (m *GetPaymentInstrumentParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPaymentInstrumentParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetPaymentInstrumentParams proto.InternalMessageInfo

func (m *GetPaymentInstrumentParams) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetPaymentInstrumentParams) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type GetPaymentInstrumentsParams struct {
	Platform             string   `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPaymentInstrumentsParams) Reset()         { *m = GetPaymentInstrumentsParams{} }
func (m *GetPaymentInstrumentsParams) String() string { return proto.CompactTextString(m) }
func (*GetPaymentInstrumentsParams) ProtoMessage()    {}
func (*GetPaymentInstrumentsParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{9}
}

func (m *GetPaymentInstrumentsParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPaymentInstrumentsParams.Unmarshal(m, b)
}
func (m *GetPaymentInstrumentsParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPaymentInstrumentsParams.Marshal(b, m, deterministic)
}
func (m *GetPaymentInstrumentsParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPaymentInstrumentsParams.Merge(m, src)
}
func (m *GetPaymentInstrumentsParams) XXX_Size() int {
	return xxx_messageInfo_GetPaymentInstrumentsParams.Size(m)
}
func (m *GetPaymentInstrumentsParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPaymentInstrumentsParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetPaymentInstrumentsParams proto.InternalMessageInfo

func (m *GetPaymentInstrumentsParams) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

type GetPaymentInstrumentsResponse struct {
	PaymentInstruments   []*PaymentInstrument `protobuf:"bytes,1,rep,name=payment_instruments,json=paymentInstruments,proto3" json:"payment_instruments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetPaymentInstrumentsResponse) Reset()         { *m = GetPaymentInstrumentsResponse{} }
func (m *GetPaymentInstrumentsResponse) String() string { return proto.CompactTextString(m) }
func (*GetPaymentInstrumentsResponse) ProtoMessage()    {}
func (*GetPaymentInstrumentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{10}
}

func (m *GetPaymentInstrumentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPaymentInstrumentsResponse.Unmarshal(m, b)
}
func (m *GetPaymentInstrumentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPaymentInstrumentsResponse.Marshal(b, m, deterministic)
}
func (m *GetPaymentInstrumentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPaymentInstrumentsResponse.Merge(m, src)
}
func (m *GetPaymentInstrumentsResponse) XXX_Size() int {
	return xxx_messageInfo_GetPaymentInstrumentsResponse.Size(m)
}
func (m *GetPaymentInstrumentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPaymentInstrumentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPaymentInstrumentsResponse proto.InternalMessageInfo

func (m *GetPaymentInstrumentsResponse) GetPaymentInstruments() []*PaymentInstrument {
	if m != nil {
		return m.PaymentInstruments
	}
	return nil
}

func init() {
	proto.RegisterType((*CreatePaymentParams)(nil), "pepeunlimited.billing.CreatePaymentParams")
	proto.RegisterType((*Payment)(nil), "pepeunlimited.billing.Payment")
	proto.RegisterType((*GetPaymentParams)(nil), "pepeunlimited.billing.GetPaymentParams")
	proto.RegisterType((*GetPaymentsParams)(nil), "pepeunlimited.billing.GetPaymentsParams")
	proto.RegisterType((*GetPaymentsResponse)(nil), "pepeunlimited.billing.GetPaymentsResponse")
	proto.RegisterType((*CreatePaymentInstrumentParams)(nil), "pepeunlimited.billing.CreatePaymentInstrumentParams")
	proto.RegisterType((*PaymentInstrument)(nil), "pepeunlimited.billing.PaymentInstrument")
	proto.RegisterType((*DeletePaymentInstrumentParams)(nil), "pepeunlimited.billing.DeletePaymentInstrumentParams")
	proto.RegisterType((*GetPaymentInstrumentParams)(nil), "pepeunlimited.billing.GetPaymentInstrumentParams")
	proto.RegisterType((*GetPaymentInstrumentsParams)(nil), "pepeunlimited.billing.GetPaymentInstrumentsParams")
	proto.RegisterType((*GetPaymentInstrumentsResponse)(nil), "pepeunlimited.billing.GetPaymentInstrumentsResponse")
}

func init() { proto.RegisterFile("payment.proto", fileDescriptor_6362648dfa63d410) }

var fileDescriptor_6362648dfa63d410 = []byte{
	// 581 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x95, 0x4f, 0x6f, 0xd3, 0x4c,
	0x10, 0xc6, 0x65, 0xe7, 0x6d, 0x9b, 0x4c, 0x9b, 0xbe, 0x74, 0x43, 0xd4, 0xe0, 0x28, 0x25, 0xf2,
	0x01, 0xa2, 0x1e, 0x52, 0x25, 0xed, 0xa1, 0x70, 0x42, 0x80, 0x84, 0x7c, 0x8b, 0x5c, 0x38, 0x14,
	0x0e, 0x96, 0x13, 0x4f, 0x53, 0x0b, 0xc7, 0x5e, 0xed, 0x6e, 0x80, 0x44, 0xe2, 0xc0, 0x07, 0xe1,
	0xbb, 0x22, 0xdb, 0xeb, 0x7f, 0x8d, 0x4d, 0x52, 0x71, 0x8a, 0x77, 0x77, 0x66, 0x7e, 0xcf, 0xec,
	0x33, 0x76, 0xa0, 0x49, 0xed, 0xd5, 0x02, 0x7d, 0x31, 0xa4, 0x2c, 0x10, 0x01, 0x69, 0x53, 0xa4,
	0xb8, 0xf4, 0x3d, 0x77, 0xe1, 0x0a, 0x74, 0x86, 0x53, 0xd7, 0xf3, 0x5c, 0x7f, 0xae, 0x75, 0xe7,
	0x41, 0x30, 0xf7, 0xf0, 0x22, 0x0a, 0x9a, 0x2e, 0xef, 0x2e, 0x70, 0x41, 0xc5, 0x2a, 0xce, 0xd1,
	0xce, 0x1e, 0x1e, 0x7e, 0x67, 0x36, 0xa5, 0xc8, 0x78, 0x7c, 0xae, 0xff, 0x84, 0xd6, 0x3b, 0x86,
	0xb6, 0xc0, 0x49, 0x8c, 0x9a, 0xd8, 0xcc, 0x5e, 0x70, 0xf2, 0x0c, 0xea, 0x01, 0x73, 0x90, 0x59,
	0xae, 0xd3, 0x51, 0xfa, 0xca, 0xa0, 0x66, 0x1e, 0x44, 0x6b, 0xc3, 0x21, 0x63, 0x68, 0x4b, 0x59,
	0x96, 0xeb, 0x73, 0xc1, 0x96, 0xf1, 0xa3, 0xd3, 0x51, 0xa3, 0xb8, 0x96, 0x3c, 0x34, 0xd2, 0x33,
	0xc3, 0x21, 0xa7, 0x70, 0xb0, 0xe4, 0x71, 0xb5, 0x5a, 0x14, 0xb5, 0x1f, 0x2e, 0x0d, 0x47, 0xbf,
	0x87, 0x03, 0x09, 0xae, 0xae, 0xab, 0x54, 0xd7, 0xcd, 0xcb, 0x54, 0x8b, 0x32, 0x8f, 0x41, 0x4d,
	0x69, 0xaa, 0xeb, 0xe8, 0x08, 0x4f, 0x3e, 0xa0, 0x28, 0x76, 0xd9, 0x03, 0x48, 0x91, 0x09, 0xa7,
	0x91, 0x70, 0x0a, 0xaa, 0xd5, 0xbc, 0xea, 0x02, 0xb6, 0x56, 0xc0, 0xea, 0xf7, 0x70, 0x92, 0x61,
	0xb8, 0xe4, 0xe4, 0x0a, 0x29, 0x85, 0x42, 0x5d, 0x68, 0x50, 0x7b, 0x8e, 0x16, 0x77, 0xd7, 0x18,
	0x31, 0xf6, 0xcc, 0x7a, 0xb8, 0x71, 0xe3, 0xae, 0x31, 0x56, 0x37, 0x47, 0x4b, 0x04, 0x5f, 0xd1,
	0x97, 0x9c, 0x28, 0xfc, 0x63, 0xb8, 0xa1, 0xaf, 0xa0, 0x95, 0x23, 0x99, 0xc8, 0x69, 0xe0, 0x73,
	0x24, 0xaf, 0xa1, 0x2e, 0x3b, 0xe0, 0x1d, 0xa5, 0x5f, 0x1b, 0x1c, 0x8e, 0xcf, 0x86, 0xa5, 0x73,
	0x33, 0x94, 0xa9, 0x66, 0x1a, 0x4f, 0x5e, 0xc0, 0xff, 0x3e, 0xfe, 0x10, 0x56, 0x0e, 0x1b, 0x37,
	0xde, 0x0c, 0xb7, 0x27, 0x29, 0xfa, 0x12, 0x7a, 0x85, 0xa1, 0xc9, 0x3c, 0x91, 0x0d, 0x13, 0xf8,
	0x4f, 0xac, 0x28, 0x46, 0xdd, 0x36, 0xcc, 0xe8, 0x59, 0xbf, 0x85, 0x93, 0x8d, 0x70, 0xe9, 0x92,
	0x92, 0xb8, 0x94, 0x26, 0xaa, 0x59, 0x22, 0xe9, 0xc3, 0x51, 0xf8, 0x6b, 0xb9, 0xa3, 0x6b, 0x3f,
	0xbb, 0x71, 0x08, 0xf7, 0x8c, 0xd1, 0xb5, 0x6f, 0x38, 0xfa, 0x73, 0xe8, 0xbd, 0x47, 0x0f, 0x2b,
	0xf5, 0xe8, 0x6f, 0x40, 0xcb, 0xee, 0x6a, 0x43, 0x6d, 0x26, 0xa2, 0x59, 0x25, 0x42, 0x7f, 0x05,
	0xdd, 0xb2, 0x0a, 0x89, 0xc3, 0x1a, 0xd4, 0xa9, 0x67, 0x8b, 0xbb, 0x80, 0x2d, 0x64, 0xd3, 0xe9,
	0x5a, 0x5f, 0x43, 0xaf, 0x34, 0x35, 0xb5, 0xec, 0x16, 0x5a, 0x9b, 0x93, 0x9f, 0xb8, 0x37, 0xf8,
	0xbb, 0x7b, 0x59, 0x3d, 0x93, 0x6c, 0xbc, 0x21, 0x7c, 0xfc, 0x7b, 0x0f, 0x8e, 0x65, 0xe4, 0x0d,
	0xb2, 0x6f, 0xee, 0x0c, 0xc9, 0x17, 0x68, 0x16, 0xcc, 0x23, 0xe7, 0x15, 0x84, 0x92, 0xef, 0x82,
	0xb6, 0x65, 0x96, 0xc8, 0x0c, 0x0e, 0x73, 0x43, 0x49, 0xaa, 0xc4, 0x6f, 0xbc, 0x22, 0xda, 0xf9,
	0xf6, 0xc8, 0xf4, 0xbe, 0x3e, 0x01, 0x64, 0xdb, 0xe4, 0xe5, 0xd6, 0xcc, 0x1d, 0xb5, 0xaf, 0xe0,
	0xb4, 0x62, 0xaa, 0xc9, 0xd5, 0x2e, 0x57, 0xf4, 0x70, 0xae, 0xb4, 0x9d, 0xad, 0x23, 0x1c, 0x9e,
	0x96, 0x8d, 0x08, 0x19, 0x6d, 0xed, 0xed, 0x1f, 0xa0, 0xbf, 0x14, 0x68, 0x97, 0x0e, 0x26, 0x19,
	0x3f, 0x02, 0x9b, 0x18, 0x78, 0xf5, 0x98, 0x9c, 0xc4, 0xca, 0xb7, 0x47, 0x9f, 0x93, 0x2f, 0x30,
	0xa3, 0xb3, 0xe9, 0x7e, 0xf4, 0x9f, 0x74, 0xf9, 0x27, 0x00, 0x00, 0xff, 0xff, 0x2a, 0xe7, 0x64,
	0x06, 0xf8, 0x06, 0x00, 0x00,
}
