// Code generated by entc, DO NOT EDIT.

package paymentinstruments

const (
	// Label holds the string label denoting the paymentinstruments type in the database.
	Label = "payment_instruments"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// Table holds the table name of the paymentinstruments in the database.
	Table = "payment_instruments"
	// OrdersTable is the table the holds the orders relation/edge.
	OrdersTable = "payment_instruments"
	// OrdersInverseTable is the table name for the Orders entity.
	// It exists in this package in order to avoid circular dependency with the "orders" package.
	OrdersInverseTable = "orders"
	// OrdersColumn is the table column denoting the orders relation/edge.
	OrdersColumn = "orders_payment_instruments"
)

// Columns holds all SQL columns for paymentinstruments fields.
var Columns = []string{
	FieldID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the PaymentInstruments type.
var ForeignKeys = []string{
	"orders_payment_instruments",
}
