// Code generated by entc, DO NOT EDIT.

package payment

const (
	// Label holds the string label denoting the payment type in the database.
	Label = "payment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// Table holds the table name of the payment in the database.
	Table = "payments"
	// OrdersTable is the table the holds the orders relation/edge.
	OrdersTable = "orders"
	// OrdersInverseTable is the table name for the Orders entity.
	// It exists in this package in order to avoid circular dependency with the "orders" package.
	OrdersInverseTable = "orders"
	// OrdersColumn is the table column denoting the orders relation/edge.
	OrdersColumn = "payment_orders"
	// InstrumentsTable is the table the holds the instruments relation/edge.
	InstrumentsTable = "payments"
	// InstrumentsInverseTable is the table name for the Instrument entity.
	// It exists in this package in order to avoid circular dependency with the "instrument" package.
	InstrumentsInverseTable = "payment_instruments"
	// InstrumentsColumn is the table column denoting the instruments relation/edge.
	InstrumentsColumn = "instrument_payments"
)

// Columns holds all SQL columns for payment fields.
var Columns = []string{
	FieldID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Payment type.
var ForeignKeys = []string{
	"instrument_payments",
}
