// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Instrument is the predicate function for instrument builders.
type Instrument func(*sql.Selector)

// Item is the predicate function for item builders.
type Item func(*sql.Selector)

// Orders is the predicate function for orders builders.
type Orders func(*sql.Selector)

// Payment is the predicate function for payment builders.
type Payment func(*sql.Selector)

// Txs is the predicate function for txs builders.
type Txs func(*sql.Selector)
