// Code generated by entc, DO NOT EDIT.

package plans

const (
	// Label holds the string label denoting the plans type in the database.
	Label = "plans"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// Table holds the table name of the plans in the database.
	Table = "plans"
	// SubscriptionsTable is the table the holds the subscriptions relation/edge.
	SubscriptionsTable = "plans"
	// SubscriptionsInverseTable is the table name for the Subscriptions entity.
	// It exists in this package in order to avoid circular dependency with the "subscriptions" package.
	SubscriptionsInverseTable = "subscriptions"
	// SubscriptionsColumn is the table column denoting the subscriptions relation/edge.
	SubscriptionsColumn = "subscriptions_plans"
)

// Columns holds all SQL columns for plans fields.
var Columns = []string{
	FieldID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Plans type.
var ForeignKeys = []string{
	"subscriptions_plans",
}
